//Deactivation is reversible only if you later build an account-recovery or admin-reactivation flow.

import express from 'express'
import { authenticateToken } from '../auth/auth.middleware.js'
import { changeUsername, deactivateAccount, exportMyData, getMyProfile, updateMyName, updatePreferences } from './user.controller.js'
import { csrfProtection } from '../auth/csrf.middleware.js'

const router=express.Router()

router.get('/me',authenticateToken,getMyProfile)
router.patch('/me',authenticateToken,csrfProtection,updateMyName)
router.patch('/me',authenticateToken,csrfProtection,changeUsername)
router.patch('/me/preferences',authenticateToken,csrfProtection,updatePreferences)
router.patch('/me/deactivate',authenticateToken,csrfProtection,deactivateAccount)
router.get('/me/export',authenticateToken,exportMyData)

export default router;


// #* Important OAuth consideration *#
// OAuth users do not know the random password generated by the system. For them, this endpoint should eventually require:
// Recent OAuth authentication
// or
// MFA confirmation
// For the first version, document that account deactivation requires a local password.




// Phase 2.6 — Account deletion
// Because VaultX will later contain vaults, secrets, files, and shared data, permanent deletion must be carefully designed.
// For now, define this policy:
// User requests deletion
//   ↓
// Require current password
//   ↓
// Revoke all sessions
//   ↓
// Delete user account
//   ↓
// Later delete owned vaults, secrets, files, and shares

// Do not implement permanent deletion until the vault data model exists. Otherwise, future vault records could become orphaned.

// Required deletion rules
// Before deletion, decide what happens to:
// Owned vaults
// Vault members
// Secrets
// Shared items
// Files
// Audit logs
// Notifications
// Backups

// Recommended policy:
// Data	                    Action
// Owned vaults	            Delete or transfer ownership
// Personal secrets	        Delete permanently
// Shared secrets       	Revoke sharing
// Sessions             	Delete immediately
// Audit logs            	Preserve anonymized security records
// Files	                Delete encrypted files
// Notifications         	Delete


// Future endpoint
// DELETE /users/me
// Request:
// {
//   "currentPassword": "StrongPassword123!"
// }

// It must require:
// authenticateToken
//   ↓
// csrfProtection
//   ↓
// current password verification
//   ↓
// delete transaction

// Why password confirmation is required?
// A valid session may be stolen or left open on a shared computer. Requiring the current password provides an additional destructive-action check.

// For OAuth users, use:
// Recent OAuth reauthentication
// or
// MFA confirmation

// Important database concept:
// When vaults are added, deletion should use a MongoDB transaction:
// Start transaction
//   ↓
// Delete user-owned vaults
//   ↓
// Delete vault items
//   ↓
// Delete sessions
//   ↓
// Delete user
//   ↓
// Commit transaction

// If any step fails:
// Rollback everything

// Do not permanently delete only the user while leaving secrets behind.
// For now, mark account deletion as designed but deferred until Phase 3 vault ownership is implemented.